# Configuration for the Churn Prediction Project

data:
  raw_data_path: "data/customer_churn_mini.json"
  processed_data_path: "data/processed_user_features.csv"

model:
  name: "lightgbm"
  objective: "binary"
  boosting_type: "gbdt"
  save_path: "ml_artifacts/lgbm_churn_model.pkl"

params:
  n_estimators: 1000
  learning_rate: 0.05
  num_leaves: 31
  max_depth: -1
  feature_fraction: 0.8
  bagging_fraction: 0.8
  bagging_freq: 1
  lambda_l1: 0.1
  lambda_l2: 0.1
  verbose: -1
  n_jobs: -1
  seed: 42

training:
  test_size: 0.2
  random_state: 42
  early_stopping_rounds: 100

mlflow:
  experiment_name: "Churn_Prediction"
  tracking_uri: "http://127.0.0.1:5000" # Example tracking server URI
